name: Pull Request Flow
on:
  pull_request:
    branches: [main]

jobs:
  format-code:
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-terraform@v2
        with:
          terraform-version: "1.3.7"
      - uses: actions/setup-node@v2
        with:
          node-version: "16.17.0"
      - run: terraform fmt **/*.tf
      - run: npm --prefix frontend ci
      - run: npm --prefix frontend run-script fmt
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply formatting changes
          branch: ${{ github.head_ref }}
