name: Pull Request Flow
on:
  pull_request:
    branches: [main]

jobs:
  format-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.3.7"
      - uses: actions/setup-node@v3
        with:
          node-version: "16.17.0"
      - run: terraform fmt **/*.tf
      - run: npm --prefix frontend ci
      - run: npm --prefix frontend run-script fmt
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply formatting changes
          branch: ${{ github.head_ref }}
  client-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: "16.17.0"
      - run: cd frontend
      - run: npm install
      - run: npm test
  api-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-go@v3
        with:
          go-version: "1.13"
      - run: cd api && go test ./...
  cli-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-go@v3
        with:
          go-version: "1.13"
      - run: cd cli && go test ./...
